name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t aureliatech/githubdemo:latest .
          docker push aureliatech/githubdemo:latest

  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull and Test Docker Image
        run: |
          docker pull aureliatech/githubdemo:latest
          docker run --rm aureliatech/githubdemo:latest pytest test_app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Docker Container
        run: |
          docker run -d -p 5000:5000 aureliatech/githubdemo:latest
